name: Backend CI

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the "main" branch
    paths:
      - 'backend/**'   # Trigger the workflow if there are changes in the "backend" directory

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run backend tests
        run: |
          cd backend
          # Add commands to build and test the backend here
